_base_:
  - ../../default.yaml
  - ../transfusion/default.yaml

point_cloud_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
voxel_size: [0.075, 0.075, 0.2]

input_modality:
  use_lidar: true
  use_camera: false
  use_radar: false
  use_map: false
  use_external: false

model:
  type: BEVFusion
  encoders:
    camera: null
    lidar:
      voxelize:
        max_num_points: 10
        point_cloud_range: ${point_cloud_range}
        voxel_size: ${voxel_size}
        max_voxels: [120000, 160000]
      backbone:
        type: SparseEncoder
        in_channels: 5
        sparse_shape: [1440, 1440, 41]
        output_channels: 128
        order:
          - conv
          - norm
          - act
        encoder_channels:
          - [16, 16, 32]
          - [32, 32, 64]
          - [64, 64, 128]
          - [128, 128]
        encoder_paddings:
          - [0, 0, 1]
          - [0, 0, 1]
          - [0, 0, [0, 1, 1]]
          - [0, 0]
        block_type: basicblock
  fuser: null
  decoder:
    backbone:
      type: SECOND
      in_channels: 256
      out_channels:
        - 128
        - 256
      layer_nums:
        - 5
        - 5
      layer_strides:
        - 1
        - 2
      norm_cfg:
        type: BN
        eps: 0.001
        momentum: 0.01
      conv_cfg:
        type: Conv2d
        bias: false
    neck:
      type: SECONDFPN
      in_channels:
        - 128
        - 256
      out_channels:
        - 256
        - 256
      upsample_strides:
        - 1
        - 2
      norm_cfg:
        type: BN
        eps: 0.001
        momentum: 0.01
      upsample_cfg:
        type: deconv
        bias: false
      use_conv_for_no_stride: true