seed: 0
deterministic: false

checkpoint_config:
  interval: 1
  max_keep_ckpts: 
  create_symlink: False   # ← 이 줄 추가

log_config:
  interval: 50
  hooks:
    - type: TextLoggerHook
    - type: TensorboardLoggerHook
    # - type: WandbLoggerHook
    #   init_kwargs:
    #     project: 'hyundai_autonomous'         # 원하는 프로젝트 이름
    #     name: 'exp_baseline_v1'      # 실험 이름
    #     entity: 'solhee0912-kookmin-university'  # 개인 또는 팀 이름 (W&B 대시보드 URL에서 확인 가능)

load_from: null
resume_from: null

cudnn_benchmark: false
fp16:
  loss_scale: 
    growth_interval: 2000

max_epochs: 20
runner:
  type: CustomEpochBasedRunner
  max_epochs: ${max_epochs}
